name: Latest Youtube videos workflow
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6wsMDXvLDbUi6aw1xhVbNA"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr style="border:none;"><td style="border:none;"><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td style="border:none;"><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "michael.ghorb@gmail.com"
          comment_tag_name: "YOUTUBE-POST-LIST"